version: '3'
services:
    mongodb:
      image: mongo:4.1
      container_name: mongodb

    parse-server:
      image: paraffin/apiserver:latest
      restart: on-failure
      container_name: apiserver
      hostname: apiserver
      ports:
        - "127.0.0.1:5000:5000"
      environment:
        NODE_ENV: production
      env_file: apiserver.env
      depends_on:
        - mongodb

    broker:
      image: paraffin/broker:0.0.4
      restart: on-failure
      container_name: broker
      expose:
        - 1883
        - 3000
        - 2345
      environment:
        NODE_ENV: production
      env_file: broker.env
      depends_on:
        - mongodb
